name: BIM coordination
favicon: null
layout_spectrum: 0.25406
typography_spectrum: 0.40522
title: BIM Coordination
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8f8f8f'
    - '#3f3f3f'
    - '#8ddc8c'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
