name: BIM coordination
favicon: null
layout_spectrum: 0.4985
typography_spectrum: 0.40522
title: BIM Coordination
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5f5f5f'
    - '#202020'
    - '#afafaf'
    - '#0807c5'
  brandStrength: 0.0625
  lightness: 0.2980476969387382
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
