name: BIM coordination
favicon: null
layout_spectrum: 0.25406
typography_spectrum: 0.40522
title: BIM Coordination
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#b4d3f0'
    - '#74abe4'
    - '#772103'
    - '#cd601f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
