name: bimcoordination
favicon: null
layout_spectrum: 0.3238
typography_spectrum: 0.3992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#979797'
    - '#202020'
    - '#7b716f'
    - '#484848'
  brandStrength: 0.5933037407230586
  lightness: 0.2980476969387382
  saturation: 0.7282870297785848
  rhythmicContrast: 0.09197832411155105
purpose: []
