name: BIM coordination
favicon: null
layout_spectrum: 0.25406
typography_spectrum: 0.40522
title: BIM Coordination
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#1155cc'
    - '#4889f1'
    - '#b0b0b0'
    - '#292929'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
